name: Octahe release

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKERUSER }}
        password: ${{ secrets.DOCKERPASS }}
        repository: peznauts/octahe
        tag_with_ref: true
        tag_with_sha: true
        add_git_labels: true
        push: true
        tags: stable

  linux_artifact:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: fwal/setup-swift@v1
    - name: Install dev requirements
      run: sudo apt install -y libssl-dev
    - name: Build Octahe
      run: swift build --configuration release -Xswiftc -g
    - name: Upload Octahe release
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: .build/release/octahe
        asset_name: octahe-x86-linux
        asset_content_type: application/octet-stream

  macos_artifact:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install libressl
      run: brew install libressl
    - name: Build Octahe
      run: swift build --configuration release -Xswiftc -g
      env:
        LDFLAGS: "-L/usr/local/opt/libressl/lib"
        CPPFLAGS: "-I/usr/local/opt/libressl/include"
        PKG_CONFIG_PATH: "/usr/local/opt/libressl/lib/pkgconfig"
    - name: Upload Octahe release
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: .build/release/octahe
        asset_name: octahe-x86-macosx
        asset_content_type: application/octet-stream

  macos_dmg:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install libressl
      run: brew install libressl
    - name: Build Octahe
      run: swift build --configuration release -Xswiftc -g
      env:
        LDFLAGS: "-L/usr/local/opt/libressl/lib"
        CPPFLAGS: "-I/usr/local/opt/libressl/include"
        PKG_CONFIG_PATH: "/usr/local/opt/libressl/lib/pkgconfig"
    - name: Install build DMG
      run: ./scripts/dmg-build.sh
    - name: Upload Octahe release
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: .build/octahe-install.dmg
        asset_name: octahe-x86-macosx-install.dmg
        asset_content_type: application/octet-stream
